name: apk
description: "Projeto do aplicativo TimeRoom"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Calendário
  table_calendar: ^3.0.9

  # Supabase
  supabase_flutter: ^2.5.4

  # Variáveis de ambiente
  flutter_dotenv: ^5.2.0

  # Internacionalização
  intl: ^0.18.1

  # QR Code
  qr_code_scanner_plus: ^2.0.12
  qr_flutter: ^4.1.0

  # Armazenamento seguro
  flutter_secure_storage: ^9.2.2

  # Preferências locais
  shared_preferences: ^2.3.2

  # Autenticação biométrica
  local_auth: ^2.2.0

  # Compartilhar conteúdo
  share_plus: ^12.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.1.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_fundo.png
    - assets/logo_ponteiro.png
    - assets/LogoHorizontal.png
    - assets/logo_ellipse.png
    - assets/logo_retangulo.png
    - .env
