name: apk
description: "Projeto do aplicativo TimeRoom"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  table_calendar: ^3.0.9
  supabase_flutter: ^2.5.4
  flutter_dotenv: ^5.2.0
  intl: ^0.18.1
  qr_code_scanner_plus: ^2.0.12
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  local_auth: ^2.2.0
  share_plus: ^12.0.0
  image_picker: ^1.0.7
  path: ^1.8.3
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/logo.png
    - assets/logo1.png
    - assets/logo_fundo.png
    - assets/logo_ponteiro.png
    - assets/LogoHorizontal.png
    - assets/LogoHorizontal1.png
    - assets/logo_ellipse.png
    - assets/logo_retangulo.png
    - .env

# Configuração do ícone e nome do app
flutter_icons:
  android: true
  image_path: "assets/icon.png" # caminho atualizado
  adaptive_icon_background: "#1ABC9C" # fundo verde para Android 8+
  adaptive_icon_foreground: "assets/icon.png"
  app_name: "TimeRoom"
